// 🚨 DO NOT EDIT DIRECTLY! 🚨
// This file was auto-generated by scripts/generate-icons-types.mts
// Changes will be overwritten when the script is run again.
// To add an icon, create a [NAME]-[SIZE].svg file in the src/icons/size-[SIZE] directory.
export type IconColor =
  | 'icon'
  | 'icon-brand'
  | 'icon-brand-pressed'
  | 'icon-brand-secondary'
  | 'icon-brand-tertiary'
  | 'icon-component'
  | 'icon-component-pressed'
  | 'icon-component-secondary'
  | 'icon-component-tertiary'
  | 'icon-danger'
  | 'icon-danger-hover'
  | 'icon-danger-pressed'
  | 'icon-danger-secondary'
  | 'icon-danger-secondary-hover'
  | 'icon-danger-tertiary'
  | 'icon-disabled'
  | 'icon-hover'
  | 'icon-onbrand'
  | 'icon-onbrand-secondary'
  | 'icon-onbrand-tertiary'
  | 'icon-oncomponent'
  | 'icon-oncomponent-secondary'
  | 'icon-oncomponent-tertiary'
  | 'icon-ondanger'
  | 'icon-ondanger-secondary'
  | 'icon-ondanger-tertiary'
  | 'icon-ondisabled'
  | 'icon-oninverse'
  | 'icon-onselected'
  | 'icon-onselected-secondary'
  | 'icon-onselected-strong'
  | 'icon-onselected-tertiary'
  | 'icon-onsuccess'
  | 'icon-onsuccess-secondary'
  | 'icon-onsuccess-tertiary'
  | 'icon-onwarning'
  | 'icon-onwarning-secondary'
  | 'icon-onwarning-tertiary'
  | 'icon-pressed'
  | 'icon-secondary'
  | 'icon-secondary-hover'
  | 'icon-selected'
  | 'icon-selected-secondary'
  | 'icon-selected-tertiary'
  | 'icon-success'
  | 'icon-success-pressed'
  | 'icon-success-secondary'
  | 'icon-success-tertiary'
  | 'icon-tertiary'
  | 'icon-tertiary-hover'
  | 'icon-warning'
  | 'icon-warning-pressed'
  | 'icon-warning-secondary'
  | 'icon-warning-tertiary';

export type IconSize = 8 | 12 | 16 | 32;

export type IconName =
  | 'control-chevron-down'
  | 'control-chevron-up'
  | 'control-checkbox-checked'
  | 'control-checkbox-mixed'
  | 'align-bottom'
  | 'align-middle'
  | 'align-top'
  | 'anchor-horizontal'
  | 'anchor-vertical'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-left-right'
  | 'arrow-right'
  | 'arrow-up'
  | 'arrow-up-down'
  | 'auto-layout-horizontal-bottom'
  | 'auto-layout-horizontal-center'
  | 'auto-layout-horizontal-top'
  | 'auto-layout-vertical-center'
  | 'auto-layout-vertical-left'
  | 'auto-layout-vertical-right'
  | 'caret-down'
  | 'caret-left'
  | 'caret-right'
  | 'caret-up'
  | 'chevron-down'
  | 'chevron-up'
  | 'circle-help'
  | 'circle-info'
  | 'code'
  | 'connector'
  | 'hyperlink'
  | 'layer-animated'
  | 'layer-component'
  | 'layer-ellipse'
  | 'layer-frame'
  | 'layer-frame-cover-art'
  | 'layer-frame-scrolling'
  | 'layer-frame-scrolling-horizontal'
  | 'layer-frame-scrolling-vertical'
  | 'layer-group'
  | 'layer-image'
  | 'layer-instance'
  | 'layer-line'
  | 'layer-mask'
  | 'layer-rectangle'
  | 'layer-slice'
  | 'layer-text'
  | 'layer-vector'
  | 'lock-locked'
  | 'lock-unlocked'
  | 'menu-checkmark-breadcrumb'
  | 'menu-checkmark-checked'
  | 'menu-checkmark-mixed'
  | 'move-down'
  | 'move-right'
  | 'option-check'
  | 'option-disabled'
  | 'orientation-landscape'
  | 'orientation-portrait'
  | 'padding-horizontal'
  | 'padding-vertical'
  | 'space-horizontal'
  | 'space-vertical'
  | 'star'
  | 'star-filled'
  | 'swap'
  | 'target'
  | 'text-align-center'
  | 'text-align-justified'
  | 'text-align-left'
  | 'text-align-right'
  | 'text-decoration-strikethrough'
  | 'text-decoration-underline'
  | 'upload'
  | 'visibility-hidden'
  | 'visibility-visible'
  | 'warning'
  | 'world'
  | 'adjust'
  | 'angle'
  | 'animation'
  | 'arrow-down-circle'
  | 'arrow-left-circle'
  | 'arrow-right-circle'
  | 'arrow-up-circle'
  | 'bell'
  | 'blend'
  | 'blend-empty'
  | 'check-circle'
  | 'check-circle-filled'
  | 'chevron-left'
  | 'chevron-right'
  | 'component'
  | 'connection-connect'
  | 'connection-delete'
  | 'corner-radius'
  | 'corners'
  | 'cross'
  | 'distribute-horizontal-spacing'
  | 'distribute-vertical-spacing'
  | 'draft'
  | 'effects'
  | 'ellipsis'
  | 'eyedropper'
  | 'folder'
  | 'frame'
  | 'grid'
  | 'hyperlink-break'
  | 'hyperlink-linked'
  | 'info'
  | 'layout-align-bottom'
  | 'layout-align-horizontal-centers'
  | 'layout-align-left'
  | 'layout-align-right'
  | 'layout-align-top'
  | 'layout-align-vertical-centers'
  | 'layout-grid-columns'
  | 'layout-grid-rows'
  | 'layout-grid-uniform'
  | 'layout-horizontal'
  | 'layout-vertical'
  | 'letter-spacing'
  | 'library'
  | 'line-height'
  | 'link-break'
  | 'link-linked'
  | 'list'
  | 'list-detailed'
  | 'megaphone'
  | 'minus'
  | 'missing-fonts'
  | 'navigate-back'
  | 'navigate-to'
  | 'notice'
  | 'paragraph-indent'
  | 'paragraph-spacing'
  | 'pencil'
  | 'play'
  | 'plugin'
  | 'plus'
  | 'recent'
  | 'reset-instance'
  | 'resize-to-fit'
  | 'return'
  | 'rotate'
  | 'scale'
  | 'search'
  | 'search-large'
  | 'share'
  | 'smiley'
  | 'spacing-horizontal'
  | 'spacing-vertical'
  | 'stroke-weight'
  | 'styles'
  | 'tidy-grid'
  | 'tidy-list-horizontal'
  | 'tidy-list-vertical'
  | 'timer'
  | 'trash'
  | 'vector-handles'
  | 'warning-filled';

type IconSizesByName = {
  'control-chevron-down': [8];
  'control-chevron-up': [8];
  'control-checkbox-checked': [12];
  'control-checkbox-mixed': [12];
  'align-bottom': [16];
  'align-middle': [16];
  'align-top': [16];
  'anchor-horizontal': [16];
  'anchor-vertical': [16];
  'arrow-down': [16];
  'arrow-left': [16];
  'arrow-left-right': [16, 32];
  'arrow-right': [16];
  'arrow-up': [16];
  'arrow-up-down': [16, 32];
  'auto-layout-horizontal-bottom': [16];
  'auto-layout-horizontal-center': [16];
  'auto-layout-horizontal-top': [16];
  'auto-layout-vertical-center': [16];
  'auto-layout-vertical-left': [16];
  'auto-layout-vertical-right': [16];
  'caret-down': [16];
  'caret-left': [16];
  'caret-right': [16];
  'caret-up': [16];
  'chevron-down': [16, 32];
  'chevron-up': [16, 32];
  'circle-help': [16];
  'circle-info': [16];
  code: [16, 32];
  connector: [16];
  hyperlink: [16];
  'layer-animated': [16];
  'layer-component': [16];
  'layer-ellipse': [16];
  'layer-frame': [16];
  'layer-frame-cover-art': [16];
  'layer-frame-scrolling': [16];
  'layer-frame-scrolling-horizontal': [16];
  'layer-frame-scrolling-vertical': [16];
  'layer-group': [16];
  'layer-image': [16];
  'layer-instance': [16];
  'layer-line': [16];
  'layer-mask': [16];
  'layer-rectangle': [16];
  'layer-slice': [16];
  'layer-text': [16];
  'layer-vector': [16];
  'lock-locked': [16, 32];
  'lock-unlocked': [16, 32];
  'menu-checkmark-breadcrumb': [16];
  'menu-checkmark-checked': [16];
  'menu-checkmark-mixed': [16];
  'move-down': [16];
  'move-right': [16];
  'option-check': [16];
  'option-disabled': [16];
  'orientation-landscape': [16];
  'orientation-portrait': [16];
  'padding-horizontal': [16, 32];
  'padding-vertical': [16, 32];
  'space-horizontal': [16];
  'space-vertical': [16];
  star: [16, 32];
  'star-filled': [16, 32];
  swap: [16, 32];
  target: [16, 32];
  'text-align-center': [16];
  'text-align-justified': [16];
  'text-align-left': [16];
  'text-align-right': [16];
  'text-decoration-strikethrough': [16];
  'text-decoration-underline': [16];
  upload: [16];
  'visibility-hidden': [16, 32];
  'visibility-visible': [16, 32];
  warning: [16, 32];
  world: [16, 32];
  adjust: [32];
  angle: [32];
  animation: [32];
  'arrow-down-circle': [32];
  'arrow-left-circle': [32];
  'arrow-right-circle': [32];
  'arrow-up-circle': [32];
  bell: [32];
  blend: [32];
  'blend-empty': [32];
  'check-circle': [32];
  'check-circle-filled': [32];
  'chevron-left': [32];
  'chevron-right': [32];
  component: [32];
  'connection-connect': [32];
  'connection-delete': [32];
  'corner-radius': [32];
  corners: [32];
  cross: [32];
  'distribute-horizontal-spacing': [32];
  'distribute-vertical-spacing': [32];
  draft: [32];
  effects: [32];
  ellipsis: [32];
  eyedropper: [32];
  folder: [32];
  frame: [32];
  grid: [32];
  'hyperlink-break': [32];
  'hyperlink-linked': [32];
  info: [32];
  'layout-align-bottom': [32];
  'layout-align-horizontal-centers': [32];
  'layout-align-left': [32];
  'layout-align-right': [32];
  'layout-align-top': [32];
  'layout-align-vertical-centers': [32];
  'layout-grid-columns': [32];
  'layout-grid-rows': [32];
  'layout-grid-uniform': [32];
  'layout-horizontal': [32];
  'layout-vertical': [32];
  'letter-spacing': [32];
  library: [32];
  'line-height': [32];
  'link-break': [32];
  'link-linked': [32];
  list: [32];
  'list-detailed': [32];
  megaphone: [32];
  minus: [32];
  'missing-fonts': [32];
  'navigate-back': [32];
  'navigate-to': [32];
  notice: [32];
  'paragraph-indent': [32];
  'paragraph-spacing': [32];
  pencil: [32];
  play: [32];
  plugin: [32];
  plus: [32];
  recent: [32];
  'reset-instance': [32];
  'resize-to-fit': [32];
  return: [32];
  rotate: [32];
  scale: [32];
  search: [32];
  'search-large': [32];
  share: [32];
  smiley: [32];
  'spacing-horizontal': [32];
  'spacing-vertical': [32];
  'stroke-weight': [32];
  styles: [32];
  'tidy-grid': [32];
  'tidy-list-horizontal': [32];
  'tidy-list-vertical': [32];
  timer: [32];
  trash: [32];
  'vector-handles': [32];
  'warning-filled': [32];
};

type IconsBySize = {
  8: ['control-chevron-down', 'control-chevron-up'];
  12: ['control-checkbox-checked', 'control-checkbox-mixed'];
  16: [
    'align-bottom',
    'align-middle',
    'align-top',
    'anchor-horizontal',
    'anchor-vertical',
    'arrow-down',
    'arrow-left',
    'arrow-left-right',
    'arrow-right',
    'arrow-up',
    'arrow-up-down',
    'auto-layout-horizontal-bottom',
    'auto-layout-horizontal-center',
    'auto-layout-horizontal-top',
    'auto-layout-vertical-center',
    'auto-layout-vertical-left',
    'auto-layout-vertical-right',
    'caret-down',
    'caret-left',
    'caret-right',
    'caret-up',
    'chevron-down',
    'chevron-up',
    'circle-help',
    'circle-info',
    'code',
    'connector',
    'hyperlink',
    'layer-animated',
    'layer-component',
    'layer-ellipse',
    'layer-frame',
    'layer-frame-cover-art',
    'layer-frame-scrolling',
    'layer-frame-scrolling-horizontal',
    'layer-frame-scrolling-vertical',
    'layer-group',
    'layer-image',
    'layer-instance',
    'layer-line',
    'layer-mask',
    'layer-rectangle',
    'layer-slice',
    'layer-text',
    'layer-vector',
    'lock-locked',
    'lock-unlocked',
    'menu-checkmark-breadcrumb',
    'menu-checkmark-checked',
    'menu-checkmark-mixed',
    'move-down',
    'move-right',
    'option-check',
    'option-disabled',
    'orientation-landscape',
    'orientation-portrait',
    'padding-horizontal',
    'padding-vertical',
    'space-horizontal',
    'space-vertical',
    'star',
    'star-filled',
    'swap',
    'target',
    'text-align-center',
    'text-align-justified',
    'text-align-left',
    'text-align-right',
    'text-decoration-strikethrough',
    'text-decoration-underline',
    'upload',
    'visibility-hidden',
    'visibility-visible',
    'warning',
    'world',
  ];
  32: [
    'arrow-left-right',
    'arrow-up-down',
    'chevron-down',
    'chevron-up',
    'code',
    'lock-locked',
    'lock-unlocked',
    'padding-horizontal',
    'padding-vertical',
    'star',
    'star-filled',
    'swap',
    'target',
    'visibility-hidden',
    'visibility-visible',
    'warning',
    'world',
    'adjust',
    'angle',
    'animation',
    'arrow-down-circle',
    'arrow-left-circle',
    'arrow-right-circle',
    'arrow-up-circle',
    'bell',
    'blend',
    'blend-empty',
    'check-circle',
    'check-circle-filled',
    'chevron-left',
    'chevron-right',
    'component',
    'connection-connect',
    'connection-delete',
    'corner-radius',
    'corners',
    'cross',
    'distribute-horizontal-spacing',
    'distribute-vertical-spacing',
    'draft',
    'effects',
    'ellipsis',
    'eyedropper',
    'folder',
    'frame',
    'grid',
    'hyperlink-break',
    'hyperlink-linked',
    'info',
    'layout-align-bottom',
    'layout-align-horizontal-centers',
    'layout-align-left',
    'layout-align-right',
    'layout-align-top',
    'layout-align-vertical-centers',
    'layout-grid-columns',
    'layout-grid-rows',
    'layout-grid-uniform',
    'layout-horizontal',
    'layout-vertical',
    'letter-spacing',
    'library',
    'line-height',
    'link-break',
    'link-linked',
    'list',
    'list-detailed',
    'megaphone',
    'minus',
    'missing-fonts',
    'navigate-back',
    'navigate-to',
    'notice',
    'paragraph-indent',
    'paragraph-spacing',
    'pencil',
    'play',
    'plugin',
    'plus',
    'recent',
    'reset-instance',
    'resize-to-fit',
    'return',
    'rotate',
    'scale',
    'search',
    'search-large',
    'share',
    'smiley',
    'spacing-horizontal',
    'spacing-vertical',
    'stroke-weight',
    'styles',
    'tidy-grid',
    'tidy-list-horizontal',
    'tidy-list-vertical',
    'timer',
    'trash',
    'vector-handles',
    'warning-filled',
  ];
};

// Utility types
export type IconOfSize<S extends IconSize> = IconsBySize[S][number];
export type SizeForIcon<T extends IconName> = IconSizesByName[T][number];
export type Icon<S extends IconSize | IconName> = S extends IconSize
  ? IconOfSize<S>
  : S extends IconName
    ? SizeForIcon<S>
    : never;
