#!/usr/bin/env bash
set -eo pipefail

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

echo "⚠️ LINT IS DISABLED❗" # moon run :check :typecheck --affected --status=staged

